language: node_js
node_js:
  - "10"
cache:
  npm: true
  directories:
    - /home/travis/.rvm/

script:
  - echo "Deploy!!"
  - pushd functions
  - npm i
  - popd
install:
  - npm install -g firebase-tools
after_success:
  #  - firebase deploy --projectId cmmc-dsc1 --token $FIREBASE_TOKEN
  - firebase deploy --token $FIREBASE_TOKEN
