language: node_js
node_js:
  - "7"
cache: npm
script:
  - echo "Deploy!!"
  - pushd functions
  - npm i
  - popd
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --projectId cmmc-dsc1 --token $FIREBASE_TOKEN
