language: node_js
node_js:
  - '10'
cache:
  pip: true
  npm: true
  directories:
    - "/home/travis/.rvm/"
    - node_modules
    - "$(npm config get prefix)/lib/node_modules/firebase-tools"
script:
  - echo "Deploy!!"
  - echo "Deploy!!"
  - pushd functions
  - npm i
  - popd
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN

before_deploy: "echo 'ready?'"
deploy:
  skip_cleanup: true
  on:
    branch: master
    tags: false
  provider: firebase
  token:
    secure: "RWkRJwGWbue6aQuLq+rN/5VMt421ndmyVrkw5+jMKVt6GJ0KGlE9z4R32JqrN2WrYkc8mJWq3cf9i/9vwovnknJIInz0Yl/vxdKAACCvl/ViGoqFzUOmlttG2vJxUuW647/AMdvMQC1oqzwKw2LP+odc05kOvoR38mv+xs2GVSx3wg7Ur6GB2Jm/QD0+YYz/v5AiMUZEO/2kJ/J6G3RZVdk1RNY2yCMaYkWnReK8+GC5CxEXxurPxezW92He1wrwFmmV2syhqXCgXuWFQcd3+dhZh1BYNOM7A0VsSoHqof3GXEq45y7LsXYgLGQ3g/jAaqFT0D6yCM9dYsMPVn+8d/sDBk1URtMH0gguTcVVE1vwQ0d3MAgWXsQ8wgG9pM5T0t4w7FWoncyuWRTVf2+wnWdwTgDVwUXzISoegfgLiRda5pvhW42UWJvkh0fiHsGPAnk2XWovJiJW0mtirbVYscSrGcVlh427Su5HnNCMPGdjFqOaUJPmgUXdk+SctaGXoHwBRPWZf332ifvcQKEhuQLmqdTIN3LfhFGD7qhR9CQMYZCM88NSKnZuQ45/jQMZFjXVJE83c0KtRbYQgWtB4Gcjw4lbDWCAN89ZUdrJZb5iPQuIJ8XaINoKK+AnTwf3tpnY24cYfZNM/Q1yDtxj7uPtgiks5PlK4GFoqPnpqLE="

  message: "your message"
  project: "cmmc-dsc1"
